
pipeline {
    agent {
        label 'catalogue'   // same agent you are using
    }

    environment {
        REGION = "us-east-1"
    }

    stages {

        stage('Terraform Init') {
            steps {
                sh 'terraform init'
            }
        }

        stage('Terraform Plan') {
            steps {
                sh 'terraform plan'
            }
        }

        stage('Terraform Apply') {
            steps {
                sh 'terraform apply -auto-approve'
            }
        }
    }

    post {
        success {
            echo "✅ VPC Peering Done"
        }
        failure {
            echo "❌ Peering Failed"
        }
    }
}
