pipeline {
    agent {
        label 'catalogue'
    }

    stages {

        stage('Terraform Init') {
            steps {
                sh '''
                cd 90-vpc-peering
                terraform init
                '''
            }
        }

        stage('Terraform Plan') {
            steps {
                sh '''
                cd 90-vpc-peering
                terraform plan
                '''
            }
        }

        stage('Terraform Apply') {
            steps {
                sh '''
                cd 90-vpc-peering
                terraform apply -auto-approve
                '''
            }
        }
    }

    post {
        success {
            echo "✅ VPC Peering Done"
        }
        failure {
            echo "❌ Peering Failed"
        }
    }
}
