pipeline {
    agent {
        label 'catalogue'
    }

    environment {
        REGION = "us-east-1"
    }

    stages {

        stage('Terraform Init') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: REGION) {
                        sh '''
                        cd 90-vpc-peering
                        terraform init
                        '''
                    }
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: REGION) {
                        sh '''
                        cd 90-vpc-peering
                        terraform plan
                        '''
                    }
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: REGION) {
                        sh '''
                        cd 90-vpc-peering
                        terraform apply -auto-approve
                        '''
                    }
                }
            }
        }
    }

    post {
        success {
            echo "✅ VPC Peering Done"
        }
        failure {
            echo "❌ Peering Failed"
        }
    }
}
